<div id="elefunds_share">
    <h3><?php echo $view['tellAboutIt']; ?></h3>
    <p><?php echo $view['IDonatedAndWantToTellAboutIt']; ?></p>
    <?php foreach($view['shares'] as $share): ?>
        <a title="<?php echo $share->title ?>" href="<?php echo $share->url; ?>" onclick="return elefunds_share('<?php echo $share->url; ?>', <?php echo $share->width; ?>, <?php echo $share->height; ?>)">
            <img src="<?php echo $share->imageUrl; ?>" />
        </a>
        &nbsp;&nbsp;
    <?php endforeach; ?>
    <span>Erfahre mehr über <a href="http://elefunds.de" target="_blank"><img src="https://bbbf9fd0e36d5cb36b93-c1fc539e0df6af03ccc14b5020ab4161.ssl.cf1.rackcdn.com/default/elefunds_logo_s.png"></a></span>
</div>
<script language="javascript" type="text/javascript">
    function elefunds_share(url, title, width, height) {
        newwindow=window.open(url,title,'left=100,top=50,width='+width+',height='+height);
        if (window.focus) {newwindow.focus()}
        return false;
    }
</script>