<div id="elefunds">
    <input type="hidden" id="elefunds_donation_cent" value="<?php echo $view['suggestedDonationAmountCent']; ?>" name="elefunds_donation_cent"/>
    <input type="hidden" id="<?php echo 'elefunds_suggested_round_up_cent'; ?>" name="<?php echo 'elefunds_suggested_round_up_cent'; ?>" value="<?php echo $view['suggestedDonationAmountCent'];?>"/>
    <div id="elefunds_top" style="width: <?php echo $view['actualShopWidth']; ?>px;">
        <img src="https://0ce8ff584bf613ee6639-c1fc539e0df6af03ccc14b5020ab4161.ssl.cf1.rackcdn.com/<?php echo $view['theme'] ?>/elefunds_logo.png" id="elefunds_logo" class="tiptip" desc="<?php echo $view['elefundsDescription']; ?>" title="elefunds" />
        <div>
            <div id="elefunds_arrow">
                <input type="checkbox" id="elefunds_checkbox" name="elefunds_agree"/>
                <label for="elefunds_checkbox"><?php echo $view['slogan'];?></label>
                <span id="elefunds_arrow_end"></span>
            </div>
            <div id="elefunds_plus_minus">
                <a href="#" onclick="elefunds.decreaseDonation(); return false;" id="elefunds_decrease"><img src="https://0ce8ff584bf613ee6639-c1fc539e0df6af03ccc14b5020ab4161.ssl.cf1.rackcdn.com/<?php echo $view['theme'] ?>/minus.png"></a> <a href="#" onclick="elefunds.increaseDonation(); return false;" id="elefunds_increase"><img src="https://0ce8ff584bf613ee6639-c1fc539e0df6af03ccc14b5020ab4161.ssl.cf1.rackcdn.com/<?php echo $view['theme'] . '/' . $view['color'] ?>/plus.png"></a>
            </div>
            <div id="elefunds_input_container">
                <label id="elefunds_currency" for="elefunds_input"><?php echo $view['currency']; ?></label>
                <input type="text" id="elefunds_input" name="elefunds_round_up" onkeyup="elefunds.donationChange(this.value)" value="<?php echo $view['suggestedDonationAmount'];?>" />
            </div>
        </div>
    </div>
    
    <div id="elefunds_bottom" style="width: <?php echo $view['actualShopWidth']; ?>px;">
        <?php $numReceivers = count($view['receivers']); $i = 0; foreach ($view['receivers'] as $key => $receiver): ?>
        <input type="hidden" name="elefunds_receiver_name[]" value="<?php echo $receiver->getName(); ?>" />
        <div class="elefunds_receiver tiptip" desc="<?php echo $receiver->getDescription(); ?>" title="<?php echo $receiver->getName(); ?>">
            <input type="checkbox" id="<?php echo 'elefunds_receiver_' . $receiver->getId(TRUE); ?>" name="elefunds_receivers[]" value="<?php echo $receiver->getId(TRUE); ?>"/>
            <?php if(++$i !== $numReceivers)  : ?>
                <label for="<?php echo 'elefunds_receiver_' . $receiver->getId(TRUE); ?>" style="padding: 12px <?php echo $view['paddingRight']; ?> 8px <?php echo $view['paddingLeft']; ?>;"><img src="<?php echo $receiver->getImage('horizontal', 'medium'); ?>" /></label>
            <?php else : ?>
                <label for="<?php echo 'elefunds_receiver_' . $receiver->getId(TRUE); ?>" style="padding: 12px <?php echo $view['paddingRightLast']; ?> 8px <?php echo $view['paddingLeftLast']; ?>;"><img src="<?php echo $receiver->getImage('horizontal', 'medium'); ?>" /></label>
            <?php endif; ?>
        </div>
        <?php endforeach; ?>
    </div>

    <div id="elefunds_below_container" style="width: <?php echo $view['actualShopWidth']; ?>px; display: none;">
        <?php if ($view['offerDonationReceipt']): ?>
        <div id="elefunds_receipt">
            <input type="checkbox" name="elefunds_receipt" id="elefunds_receipt_checkbox" /><label for="elefunds_receipt_checkbox"><?php echo $view['receipt_slogan'];?></label>
        </div>
        <?php endif; ?>
        <div id="elefunds_round_sum_container" class="elefunds_hidden">
            <strong><?php echo $view['roundedSumString']; ?></strong>
            <strong id="elefunds_round_sum"><?php echo $view['roundedSum'];?></strong>
            <strong><?php echo $view['currency']; ?></strong>
        </div>
    </div>
</div>

<script type="text/javascript">
jQuery('<img src="https://0ce8ff584bf613ee6639-c1fc539e0df6af03ccc14b5020ab4161.ssl.cf1.rackcdn.com/<?php echo $view['theme'] . '/' . $view['color'] ?>/arrow_on.png"/>');
jQuery('<img src="https://0ce8ff584bf613ee6639-c1fc539e0df6af03ccc14b5020ab4161.ssl.cf1.rackcdn.com/checkbox_on.png"/>');
jQuery('<img src="https://0ce8ff584bf613ee6639-c1fc539e0df6af03ccc14b5020ab4161.ssl.cf1.rackcdn.com/receiver_on_bg.png"/>');
jQuery('<img src="https://0ce8ff584bf613ee6639-c1fc539e0df6af03ccc14b5020ab4161.ssl.cf1.rackcdn.com/receipt_on.png"/>');

var elefunds = (function(parent, $) {
    var options = {
        roundSumContainer: $('#<?php echo $view["roundSumContainer"]; ?>'),
        roundSum: $('#<?php echo $view["roundSum"]; ?>'),
        currency: '<?php echo $view["currency"]; ?>',
        decimal: '<?php echo $view["currencyDelimiter"]; ?>',
        decimalAlt: ',',
        total: <?php echo $view["total"]; ?>,
        toolTipPosition: '<?php echo $view["toolTipPosition"]; ?>'
    };
    
    if(options.decimal === options.decimalAlt) {
        options.decimalAlt = '.';
    }
    
    if(parent.hasOwnProperty('init')) {
        parent.init(options);
    }
    
    return {
        options: options,
        
        decreaseDonation: function() {
            return parent.decreaseDonation();
        },
        
        increaseDonation: function() {
            return parent.increaseDonation();
        },
        
        donationChange: function(floatValue) {
            return parent.donationChange(floatValue);
        }
    }
    
}(window.elefunds || {}, jQuery));
</script>
